<?php
/**
 * Created by PhpStorm.
 * User: chenlongmingob@outlook.com
 * Date: 2018/11/5
 * Time: 14:33
 */

namespace app\common\component\FormDatetime;


use app\common\component\FormComponent;
use think\View;

class FormDatetime extends FormComponent
{
    public static function getParam($value, $key = null, &$data = null)
    {
        
        if (!$value || $value === '') {
            $value = null;
        }else{
            $value = strtotime($value);
        }
        return parent::getParam($value, $key, $data); // TODO: Change the autogenerated stub
    }
}